### PR TITLE
Add missing Flatpak icon symlinks

### PR DESCRIPTION
**Pull request by SakiiCode**
Added:
- Brave
- Kdenlive
- Firefox
- Remmina
- Ungoogled Chromium
- Avidemux
- Ardour
- Librewolf
- LMMS
- Zotero
- Blender
- Lutris
- Eclipse
- Dota 2
- Kodi
- Pinta

Fixed:
- MPV
- VSCode
- Obsidian

### CODE REVIEW

**Comment by anaximeno** [comment]
@SakiiCode I've sent one pull request to append to this in https://github.com/SakiiCode/mint-y-icons/pull/1 with the symlink for Zotero.

**Comment by SakiiCode** [comment]
Accepted, thank you! Can you send the same to https://github.com/SakiiCode/mint-l-icons as well?

**Comment by anaximeno** [comment]
Sure! Added on https://github.com/SakiiCode/mint-l-icons/pull/1

**Comment by CZmisaCZ** [comment]
Ello @SakiiCode I have added some as well, can you please add my [pull request](https://github.com/SakiiCode/mint-y-icons/pull/2).

**Comment by CZmisaCZ** [comment]
Sup @SakiiCode added a few more, here is my [PR](https://github.com/SakiiCode/mint-y-icons/pull/3).

**Comment by clefebvre** [comment]
@SakiiCode  don't hesitate to join https://matrix.to/#/#linuxmint-artists:matrix.org. We're looking at artwork changes for Mint 22, it'd be good to have a chat about it.

**Comment by clefebvre** [comment]
Merged in master.

**Pull request closed without merging**
