### PR TITLE
Update Firefox icon based on official logo

### PR DESCRIPTION
**Pull request by elsiehupp**
Fixes https://github.com/linuxmint/mint-y-icons/issues/236

- Logo directly taken from https://mozilla.design/firefox/logos-usage/
- Gradient taken from https://macosicons.com/

### CODE REVIEW

**Comment by elsiehupp** [comment]
I added the remaining official icons, even though, e.g., Firefox Reality is not actually available for Linux. (I'm just getting ahead of the curve.)

I mostly used gradients from existing third-party macOS icons, but they could updated with colors from the official Firefox brand colors:

https://mozilla.design/firefox/color/

Firefox Trunk doesn't appear on in the Firefox brand guidelines, but I could see what the existing official icon looks like and possibly adapt that.

**Comment by elsiehupp** [comment]
I downloaded the only copy of `firefox-trunk` I could find, and it had the same icon as `firefox-nightly`. I can't figure out how to create a symbolic link from one to the other, though.

**Comment by NikoKrause** [comment]
Hey,

thanks for contributing. The icons look good on their own, but they do not fit into Mint-Y.
Mint-Y is a flat icon theme. And those icons are not flat at all.

I think it's a nice idea to update the firefox icons.
Your icons are a good starting point to work with. We need to make them flat though. And also a more subtle change of colors. You might have a look on other icons. There are some certain style rules, which are used in (almost) all of them. I might have a look on my own in a few days.

**Comment by elsiehupp** [comment]
Okay, no worries! I honestly just did this off the cuff... My main intention here was adding the Joplin icon (in another branch). I just did these icons because it seemed like an easy thing to crank out (as the official icons are available as SVG), and because someone specifically requested it (see #236)

If you're mainly doing flat outlines on gradient backgrounds, the official Firefox brand guidelines do have monochrome SVG outlines to work with (buried inside the downloadable ZIP files), as well as official color-scheme gradients. The fox outline doesn't seem to have changed much from your previous versions, but it might be nice to distinguish the different editions with new gradients based on the official color swatches.

It would probably be good to have a clear set of design guidelines either in README.md or in a linked Markdown document. For comparison (i.e. how to compile design guidelines), you can check out [GNOME's](https://developer.gnome.org/hig/stable/icon-design.html.en), [KDE's](https://develop.kde.org/hig/style/icons/colorful/), and [Apple's](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

Again, this was kind of a drive-by contribution on my part, so please do feel free to iterate on what I've uploaded. I'm sure you have a better sense of what you want than I do!

**Comment by elsiehupp** [comment]
Here's somewhat simplified version of one of the icons:
firefox-nightly-flat
Compared to the official version from before:
firefox-nightly-official
One difficulty I feel like is that the icon just doesn't "read" as Firefox without the globe, which complicates making it completely flat.

(In all honesty, I prefer just keeping the official icons. I don't actually use this icon theme, though, so my opinion is probably not that important here.)

**Comment by NikoKrause** [comment]
The globe in the flat version needs to be purple, I think.

**Comment by NikoKrause** [comment]
Or something like this:

Screenshot_20210129_124352

https://www.reddit.com/r/firefox/comments/kh2gle/minimalist_firefox_icon/

**Comment by elsiehupp** [comment]
That's definitely a better monochrome icon than the official version!

The main issue with this file is that it's not vector, though we can see if it's available as such elsewhere online. Illustrator does support "live trace" (i.e. converting raster to vector), but the software I'm using at the moment does not. I can look into my options, though.

**Comment by elsiehupp** [comment]
I was able to extract the outline with Inkscape. (SVG [here](https://gist.github.com/elsiehupp/18838b00aae44f50ac54e5fbd2bcceb7).) Here's the main Firefox icon, with the gradient taken directly from the official version but applied to a single outline:
firefox
Versus the official logo, by comparison:
firefox-official

**Comment by elsiehupp** [comment]
(I've been posting PNG versions because (a) GitHub won't let you attach SVGs to comments, and (b) it's tedious manually creating all the smaller icon sizes for WIP snapshots.)

**Comment by elsiehupp** [comment]
Firefox Nightly/Trunk:
firefox-nightly-flat
Versus the official version:
firefox-nightly-official

**Comment by elsiehupp** [comment]
Firefox Developer:
firefox-developer
firefox-developer-official
I feel like this one isn't quite as legible against the purple background.

**Comment by NikoKrause** [comment]
I really like those versions. As a first step, i would concentrate on the main firefox logo. The other variations would be a last step since those are color variations.

Do you think you could do this icon for the other sizes as well? For the small sizes it's ok to have less details since they usually don't show as well as in bigger icon sizes.

**Comment by elsiehupp** [comment]
Yeah, doing the smaller sizes isn't difficult, just fiddly and tedious, so I wanted to wait until I got your approval on the largest size before I did the smaller ones (so I wouldn't have to redo them).

**Comment by elsiehupp** [comment]
Here are the ones I just uploaded:
firefox
firefox-trunk
`firefox-beta` is just the main icon with a little "beta" badge. And I want to figure out the gradient on `firefox-developer` before I update the SVG.

**Comment by elsiehupp** [comment]
Hypothetically I could use a simplified outline on the smaller sizes. You could tell me your opinion on the cutoff, though.

**Comment by elsiehupp** [comment]
Here's a version with the simplified outline for the smaller sizes:
firefox-nightly

**Comment by NikoKrause** [comment]
Thanks for your work done here.
This will take a few weeks to review and discuss internally, since I don't have much time right now and I think changing the firefox icon is a very sensitive subject, because it is so prominent.

**Comment by elsiehupp** [comment]
I mean, that's fine! Again, I'm not hugely hung up over it. If you want to make further changes yourselves to the work I submitted or you want to suggest any changes I could make myself, I'd be totally cool with that.

**Comment by elsiehupp** [comment]
Also FYI I would probably need to make changes to the underlying XML to make the files work with the PNG-rendering script.

**Comment by luisrguerra** [comment]
> (I've been posting PNG versions because (a) GitHub won't let you attach SVGs to comments, and (b) it's tedious manually creating all the smaller icon sizes for WIP snapshots.)
You can use [http://svgur.com](http://svgur.com) to host the svg images. To attach you just need to know a little bit of html

**Comment by elsiehupp** [comment]
Cool, these all look great!

An approach I’ve taken for attaching SVGs more recently is uploading them as GitHub gists, which keeps everything on-site.

**Comment by elsiehupp** [comment]
All these links should be stable, because I used a specific commit rather than the branch name.

**Comment by luisrguerra** [comment]
I made the gradient of the other Firefox variations:

Firefox 16x16 SVG:


Firefox Nightly 16x16 SVG:


Firefox Developer 16x16 SVG:

**Comment by clefebvre** [comment]
Hi everyone,

I spoke to Mozilla about this to get their feedback. We should stick to their original design as much as possible. They're happy for instance with the way their app looks in Android.

Like this: 

Fx-Browser-icon-fullColor-512

But with a shape around it.

**Comment by clefebvre** [comment]
image

**Comment by clefebvre** [comment]
The shape in Android is dark purple when installed, but light grey in the app store. Both work quite well.

**Comment by clefebvre** [comment]
Mozilla also provide a single color version:

Fx-Browser-icon-oneColor

I guess that means we could maybe continue to use white on top of a colored shape. It would look better when small. I'd have to go back to them and ask though. I suppose I'll have to do it either way :)

**Comment by clefebvre** [comment]
Other than this mono version and the full gradient, they don't like the idea of going in between.

**Comment by luisrguerra** [comment]
> Other than this mono version and the full gradient, they don't like the idea of going in between.

In my opinion all Web Browser icons should look like the original ones because it is easier for the user to recognize and nowadays they are well made and look good (Even when it is open source software).

**Comment by luisrguerra** [comment]
> > Other than this mono version and the full gradient, they don't like the idea of going in between.
> 
> In my opinion all web browser icons should look like the original ones because it is easier for the user to recognize and nowadays they are well made and look good (Even when it is open source software).

A more radical suggestion that would solve this problem and several others would be to change the default theme from Linux Mint to Papirus as several other Linux systems have done (Manjaro, Solus, Ubuntu Studio, Linux Lite, Mx Linux, ...). In my opinion the Papirus theme is way ahead of all the others icon themes nowadays.

**Comment by elsiehupp** [comment]
Hi Everyone—I'm archiving my fork of this repository, and since this is a pull request, I'm not sure what it'll do to this comment thread. Worst case scenario you can continue over on the original Issue here: https://github.com/linuxmint/mint-y-icons/issues/236

**Comment by clefebvre** [comment]
> Honestly the Moka theme design is very difficult to maintain. Linux Mint should abandon this style and follow the line of Material Design from Google or Fluent Design from Microsoft. This would help making progress on the development of Linux Mint interface which is very similar to the last 4 years.

@luisrguerra I'm interested in exploring this, maybe for Mint 21 or later. I like what you did here too. You're obviously very talented. Don't hesitate to create a PR to show what you mean.

I'm closing this PR since we're working on https://github.com/linuxmint/mint-y-icons/pull/294.

Thanks @elsiehupp @luisrguerra

**Pull request closed without merging**
