### PR TITLE
Flux Panel Icon

### PR DESCRIPTION
**Pull request by zystvan**
Like #30, this PR exports the SVG stored in the `ubuntu-mono-dark` directory into the `Mint-Y` directory as PNGs the correct sizes.

### CODE REVIEW

**Comment by JosephMcc** [comment]
The shutter change was merged separately so you should probably remove those here. I have to say I'm not sure I'm a huge fan of the sickly yellow/brown color these use :)

**Comment by zystvan** [comment]
@JosephMcc Sure, sorry about that. I've tried to fix it, does it look good to you now? 

> I'm not sure I'm a huge fan of the sickly yellow/brown color these use

I know, it looks pretty bad here in the file preview. It looks much better in the panel: 

screenshot from 2017-05-17 14-38-24

**Comment by JosephMcc** [comment]
Cool. In the end I can always recolor them some. I've never even seen/used the Flux thing :)

**Comment by zystvan** [comment]
I've updated this PR to match your dedda61 commit.

**Pull request merged**
