### PR TITLE
Icon for Joplin

### PR DESCRIPTION
**Pull request by elsiehupp**
Icon for Joplin based on the Discord icon. I don't know how you do linking and whatnot, so I just uploaded the SVG of all the icon sizes to the `src` folder.

I would also appreciate some help in understanding how to format the `.desktop` file so that the shell knows to use this icon. Thanks!

### CODE REVIEW

**Comment by elsiehupp** [comment]
Some further context: I added the Joplin icon here based on [this comment thread](https://discourse.joplinapp.org/t/alternative-macos-icon/8996), and I'm trying to get the Joplin `.desktop` file properly set up for theming [here](https://github.com/MrCarroll/joplin-snap/pull/11).

**Comment by NikoKrause** [comment]
Please don't add symbolic links for icons in the /src directory.

**Comment by NikoKrause** [comment]
You are right we need to do some cleanup and documentation on how to contribute.

For the time being, just add the `joplin-desktop.svg` into your PR and for the symbolic links modify the `src/symbolic-apps-list`.

E.g.
```
joplin-desktop.png <- org.joplinapp.joplin.png
```

Important here is to use the `.png` ending. 

We have scripts, which render the `joplin-desktop.svg` file to png-files and create symbolic links based on the list.

**Comment by elsiehupp** [comment]
Cool, thank you for the explanation! All set?

**Comment by NikoKrause** [comment]
Looks good to me so far. I'll check saturday on a big screen.

**Comment by NikoKrause** [comment]
Hey, sorry for taking so long to review your PR.

The icon looks good, but our script does not compile it.
You seem to have changed too much from the template though. 
I'm not sure why it doesn't compile.

The compilation is done by running the script in the `src` directory:
```
./render-apps-categories-bitmaps.py
```

What I do, if I create a new icon:
1. Copy an existing similar icon.
2. Change the gradient colors for the background.
3. Change the inner icon, in this case the "J" for Joplin, and add the shadow (as you did).
4. Open the svg file with a text-editor and change the `icon-name` id.

Render the icons with the script mentioned above.

You can try to run the command and see that your version does not compile.

Then try this version:
[joplin-desktop.svg.zip](https://github.com/linuxmint/mint-y-icons/files/5929246/joplin-desktop.svg.zip)

**Comment by elsiehupp** [comment]
I'm fairly certain the problem is that I used an intermediate format and then converted it to SVG. I can poke around in the raw XML to see what's different about the underlying structure.

**Comment by elsiehupp** [comment]
I poked around in the script, and it was calling Inkscape from an absolute path that doesn't exist on my computer. (I'm editing on my Mac, not my Linux computer.) The script also appeared to be checking for Inkscape-specific metadata. I tried opening the document in Inkscape for Mac, selecting File > Clean Up Document, and then saving it, so the XML formatting and metadata should work with the script now. FWIW you could probably stand to add more descriptive error output to the Python script. (I could take a look at this myself.)

**Comment by elsiehupp** [comment]
Could you tell me what the error message was that you were getting? I can try running the script on my Linux computer myself, as well.

**Comment by NikoKrause** [comment]
I'm not familiar with Macs.
I didn't git any error. It just didn't compile.

I need to mention, that the script doesn't work with Inkscape version 1.0 or higher.
This will be changed in the future. Right now you need Inkscape version lower than 1.0

**Comment by elsiehupp** [comment]
Does it compile now? (Again, I haven't tried running the script on my Linux computer.)

**Comment by elsiehupp** [comment]
I got the script to compile the Joplin icon, if you take a look at #284.

**Comment by elsiehupp** [comment]
Once I got the script working, I discovered that the internal name for the icon (`joplin`) didn't match the filename and the alias names (`joplin-desktop`), so I quick fixed that. The updated parsing logic that works with the Joplin icon is in Pull Request #285.

**Pull request merged**
