### PR TITLE
Add Timeshift

### PR DESCRIPTION
**Pull request by NikoKrause**
* Add deadlinks bash script from Mint-X icon theme 
* Update README

* Add src directory for svg icons and add timeshift.svg
* Timeshift SVG icon based on https://github.com/snwh/moka-icon-theme/blob/master/src/K/kile.svg
* Compiled with render-bitmaps.py script from Moka Icons Theme to get nice and beatiful png icons

### CODE REVIEW

**Comment by JosephMcc** [comment]
The icon itself looks good. Imho, it needs better versions at the smaller sizes before it gets merged.

**Comment by NikoKrause** [comment]
Yeah, working with the template from Moca

**Comment by NikoKrause** [comment]
Improved SVG icon and rebased commit.

**Comment by JosephMcc** [comment]
Nice. Looks much better.

**Pull request merged**
