### PR TITLE
Remove kotlin app icons and add mimetypes kotlin icons

### PR DESCRIPTION
**Pull request by vadimk1337**
Right now there are no icons for Kotlin at all for .kt 
I have asked [Hokiper](https://github.com/Hokiper) and [mjkim0727](https://github.com/mjkim0727) add kotlin icons because I didn't know who would win pr, the problem is that Hokiper and I did not understand each other and he added an icon for a non-existent Kotlin application, but mjkim0727 drew Kotlin mimetypes, which is correct.  So here the icons for a non-existent application kotlin are removed and the correct icons are added.

### CODE REVIEW

**Comment by clefebvre** [comment]
@Hokiper ? ^^

**Comment by clefebvre** [comment]
@vadimk1337 join us in https://app.element.io/#/room/#linuxmint-artists:matrix.org if you get a chance.

**Comment by vadimk1337** [comment]
Well, yes, in fact, I asked for an icon for mimetypes in PR about redesign **applications**, which turned out to be a little stupid on my part, so we misunderstood each other a little

**Comment by Hokiper** [comment]
> @Hokiper ? ^^

I agree with the removal of the app icon then. So do you need me design the mimetypes or you'll just use the ones in this PR?

**Comment by vadimk1337** [comment]
I would like to use this pr

**Comment by vadimk1337** [comment]
@Hokiper 
Although no, can you draw it because I don’t have svg

mint-y-icons/src/mimetypes need svg
/home/vadim/Desktop/mint-y-icons/usr/share/icons/Mint-Y/mimetypes need png
Take text-x-python.png, remove the icon from there and insert the Kotlin icon that you drew
and make pr into mint-y-icons and mint-l-icons

**Comment by vadimk1337** [comment]
@Hokiper
can you draw it? because I don’t have mjkim0727 svg 

mint-y-icons/src/mimetypes need svg
/home/vadim/Desktop/mint-y-icons/usr/share/icons/Mint-Y/mimetypes need png
Take text-x-python.png, remove the icon from there and insert the Kotlin icon that you drew
file name: text-x-kotlin
And remove kotlin from app
and make pr into mint-y-icons and mint-l-icons

**Comment by Hokiper** [comment]
Done in #419 for Mint-Y
And https://github.com/linuxmint/mint-l-icons/pull/9 for Mint-L

**Comment by vadimk1337** [comment]
cool 😏👌, nice job @Hokiper

**Pull request closed without merging**
