### PR TITLE
Update Spotify icons

### PR DESCRIPTION
**Pull request by zystvan**
The current icon theme has Spotify's old logo. I'm terrible with photo editors and such, but I tried to make these look consistent with the rest of the icons :smile:

### CODE REVIEW

**Comment by JosephMcc** [comment]
There are a couple of issues with these. If you look especially at the larger sizes you'll notice that the icon is a different size within the canvas. It doesn't have the same amount of empty space around it. This will make the icon seem to be a different size then others in the theme. Also look at the original and notice that it has a bit of a dark border or outline around it. Yours is missing that and the icon won't stand out well enough against the background.

**Comment by zystvan** [comment]
@JosephMcc Thanks for the input, I'll try to fix those issues :)

**Comment by zystvan** [comment]
@JosephMcc I'm using the Moka template thing properly now (I think), but `render-bitmaps.py` keeps generating my icons larger than they should be, for example 273 instead of 256 and 17 instead of 16 px wide/tall. Any ideas what I'm doing wrong? My Spotify SVG icon file is here if you want to download it and try yourself: 

https://www.dropbox.com/s/oq63o91tmk5o6tb/web-spotify.svg?dl=0

Other than the issue with size, do these look good now? 

![Spotify icon][1]

Thanks! 

[1]: https://cloud.githubusercontent.com/assets/7751418/22524356/e0da928c-e890-11e6-839d-c34f4279ef61.png

**Comment by zystvan** [comment]
@JosephMcc I resized them to the correct size and they have the border and shadow now. Anything else I need to fix?

**Comment by JosephMcc** [comment]
Could you squash this down to a single commit? Then I'll merge it. Thanks for putting in the effort.

**Comment by zystvan** [comment]
@JosephMcc Sure, done. 

Thanks!

**Comment by fabriziobertoglio1987** [comment]
Amazing. I love the icons!

**Pull request merged**
