### PR TITLE
Update firefox icon

### PR DESCRIPTION
**Pull request by clefebvre**
Update the Firefox icon to follow the Mozilla Logos and Usage Guidelines:

https://mozilla.design/firefox/logos-usage/

This design uses the `Icon (One Color)` SVG icon provided by Mozilla at https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Firefox-Browser-Logo-Assets.zip.

Before:

image

After:

image

### CODE REVIEW

**Comment by luisrguerra** [comment]
> Update the Firefox icon to follow the Mozilla Logos and Usage Guidelines:
> 
> https://mozilla.design/firefox/logos-usage/
> 
> This design uses the `Icon (One Color)` SVG icon provided by Mozilla at https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Firefox-Browser-Logo-Assets.zip.
> 
> Before:
> 
> image
> 
> After:
> 
> image

It's much better! please consider changing the color, this color doesn't have a good contrast with white.

**Comment by luisrguerra** [comment]
> > Update the Firefox icon to follow the Mozilla Logos and Usage Guidelines:
> > https://mozilla.design/firefox/logos-usage/
> > This design uses the `Icon (One Color)` SVG icon provided by Mozilla at https://3u26hb1g25wn1xwo8g186fnd-wpengine.netdna-ssl.com/files/2019/10/Firefox-Browser-Logo-Assets.zip.
> > Before:
> > image
> > After:
> > image
> 
> It's much better! please consider changing the color, this color doesn't have a good contrast with white.

Google's Material Design website has a tool with selected colors and shows information about contrast and color legibility.  take a look there
[Material Design Color Tool](https://material.io/resources/color/#!/?view.left=1&view.right=0&primary.color=EF6C00) 
IMG_20211117_092559

**Comment by mkaply** [comment]
The monochrome logo is OK, but the background can't be a gradient per the Firefox design guidelines.

It needs to be either Orange (#FF7139) or Ink (#20123A).

**Comment by clefebvre** [comment]
thanks @mkaply 

image

**Comment by clefebvre** [comment]
Here it in within the desktop:

image

image

I thought the absence of gradient could be a consistency issue (all other icons have a gradient bg), but it isn't that noticeable.

The #FF7139 orange is very rich, much deeper than the original one and with better contrast. It makes Firefox stand out much more than before. I think it looks great.

**Comment by SkullHex2** [comment]
Why updating one out of four Firefox logos?
Firefox Beta, Firefox Developer, Firefox Nightly logos still have the old design.

**Pull request merged**
