### PR TITLE
mimetypes: Replace our current mimetypes with the ones from the verte…

### PR DESCRIPTION
**Pull request by JosephMcc**
…x icon theme

### CODE REVIEW

**Comment by KDB2** [comment]
Hi JosephMcc,

These icons are not flat and do not really fit with the others. The original mimetypes icons from Mint-Y are looking better. 

Regards,
KDB

**Comment by JosephMcc** [comment]
@KDB2 Thanks for the feedback. There are a couple things where I have a difference of opinion from you though. The icons don't necessarily have to be in some super "flat" style. That seems to be the newer tendency but ultimately we want what looks good. The mimetypes currently used are just plain ugly. I don't see how they fit in with the app icons any better either. There is also the issue of only having them as a single size svg. That just doesn't work properly in all situations. That leaves us in a spot where we would need to create all of the additional sizes ourselves. That's a good bit of work and time to invest in something I don't really like and ultimately wouldn't want to use myself.

**Comment by KDB2** [comment]
@JosephMcc 
Thanks for your answer. I see that your choice has been driven by some technical problem. 
Of course it's only my opinion but I think that the new icons are not matching with the new folder icon. A mixture between different kind of design (flat & non flat) doesn't really look good. That's of course only my opinion, but I think these new mimetype icons too close to Mint-X. :)

Regards,
KDB

**Comment by JosephMcc** [comment]
I agree they are much closer to mint-x. The Mint-X ones are nice though because it is easy to see at a glance the different file types in a directory. That is really nice when digging through folders of code files.

Keep in mind the folder icons are subject to change as well. There is still a good bit of discussion about what we are going to end up with. I see you in IRC sometimes. Don't be afraid to drop some ideas in if you find something you think would work well.

**Comment by KDB2** [comment]
@JosephMcc 

Maybe these mimetypes could be an option: they are modern but not too much and they look different from Mint-X: https://github.com/numixproject/numix-icon-theme-utouch

For the folder, here is a lot of color choices: http://www.ravefinity.com/p/vivacious-colors-gtk-icon-theme.html
But it's not flat design and I tend to find the current Mint-Y folder more interesting.

These are only suggestions. 

KDB

**Comment by JosephMcc** [comment]
I actually have some of  Ravefinity icons installed. The problem with the mimetypes you pointed to is that many of them are dark and will not work on the dark variations of the theme. From what I've seen of the ultra-flat styled mimetypes so far, I'm really not a fan.

Even the our app icons aren't really flat. They still have borders and some shadowing that helps separate them from the background which is really lacking in the mimetypes and folders. If you hover over many of the current mimetypes in nemo they almost disappear into the background.

**Pull request closed without merging**
