### PR TITLE
[WIP] Backports from Moka icon theme

### LINKED ISSUE #15: Dangling symlinks
When packaging this for Fedora, I stumbled accross these dangling symlinks:
```
mint-y-icons.noarch: W: dangling-relative-symlink /usr/share/icons/Mint-Y/apps/96/mono-runtime-common.png mono-runtime.png
```

### LINKED ISSUE #38: Steam Icons Inconsistent
Steam icon for 96 px is wrong, different design.

### PR DESCRIPTION
**Pull request by NikoKrause**
Backports from Moka, i.e. apps and categories icons.
* Add render-bitmaps.py
* Add discord (SVG and PNG)
* Add missing WhatsApp icon
* Add Template.svg
* Update README
* Update Atom Editor icon, new one is green
* Fix battlenet icon
* Fix mono-runtime icon, Fixes #15 
* Fix steam icon, Fixes #38

### CODE REVIEW

**Comment by besser82** [comment]
@NikoKrause Could you rebase this on recent `master` branch, please?

**Comment by NikoKrause** [comment]
No. I splited this PR into separate PRs. They have been merged. Only thing here left is the render-bitmaps python script. And Joseph didn't wanted it yet.

**Comment by besser82** [comment]
Ahh…  Okie…  Didn't notice it

**Comment by clefebvre** [comment]
Marking as WIP.

**Comment by NikoKrause** [comment]
Most of the icons here have been merged with other PRs.
Only thing left is the bitmap render script.
And I don't know how/what @JosephMcc planned to handle this.

My idea is to have a source directory with all icons as svg. And the script would render the theme. And another script should create all needed symbolic links. So goal would be, that all changes/additions are made in the source directory only.

**Comment by clefebvre** [comment]
@NikoKrause can you rebase this and clean it up so we can merge it?

**Comment by clefebvre** [comment]
@NikoKrause I'll close this for now. Open a new one if you want to add the script.

**Pull request closed without merging**
